import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "./@/components/ui/Topbar";
import Sidebar from "./@/components/ui/Sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex bg-background text-foreground min-h-screen">
          <Sidebar />
          <div className="flex flex-col flex-1 ml-16">
            <TopBar />
            <main className="pt-14 p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}